### PR TITLE
Bitsch, Switzerland

### PR DESCRIPTION
**Pull request by lostfocus**

### CODE REVIEW

**Comment by vicchi** [comment]
The coordinates are the wrong way around; GeoJSON specifies them as long/lat, not as lat/long. From doing a bit of digging, it looks like 46.343095,8.0266495 (in lat/long) are also a bit more accurate. I'll make the correction as I do the merge.

**Comment by lostfocus** [comment]
Okay, that's embarrassing - I'll know for the next time. Does the (actually pretty long) [Longdong Avenue](http://goo.gl/maps/dm3ih) qualify?

**Comment by vicchi** [comment]
If it makes you snigger, it probably qualifies

**Comment by annagassan** [comment]
Hackballs Cross, Ireland
54.030562, -6.518970

**Comment by scheinsam** [comment]
Petting in Bavaria is also missing on your map. Please let me add that it's only 38 minutes from Petting to Fucking.

http://goo.gl/maps/d1tk3

**Comment by odraK** [comment]
Yorkeys Knob in Queensland Australia. Coordinates: 16°48′43″S 145°43′16″E Coordinates: 16°48′43″S 145°43′16″E

**Comment by beanbagdan** [comment]
Blowhard in Victoria Australia always makes me snigger

https://maps.google.com.au/maps?f=q&hl=en&q=blowhard&ie=UTF8

**Comment by vicchi** [comment]
@scheinsam - Petting made the last update of the map; see http://maps.geotastic.org/rude/index.php?id=203

**Comment by vicchi** [comment]
@lostfocus - see http://maps.geotastic.org/rude/index.php?id=237 and http://maps.geotastic.org/rude/index.php?id=238
@annagassan - see http://maps.geotastic.org/rude/index.php?id=239
@odraK - see http://maps.geotastic.org/rude/index.php?id=240
@beanbagdan - see http://maps.geotastic.org/rude/index.php?id=241

All added in, see commit 07965bb926520c8c18578dac79abe8e7c7e368eb

**Pull request closed without merging**
